CREATE STREAM USER_GAME (USER_KEY STRUCT<USER VARCHAR, GAME_NAME VARCHAR >, GAME STRUCT<SCORE INT, LIVES INT, LEVEL INT>) WITH (KAFKA_TOPIC='USER_GAME', KEY_FORMAT='JSON', VALUE_FORMAT='JSON');
CREATE STREAM USER_LOSSES (USER_KEY STRUCT<USER VARCHAR, GAME_NAME VARCHAR > ) WITH (KAFKA_TOPIC='USER_LOSSES', KEY_FORMAT='JSON', VALUE_FORMAT='JSON');
